[package]
name = "zebra"
version = "0.1.0"
authors = ["Matteo Monti <matteo.monti@epfl.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drop = { git = "https://github.com/Distributed-EPFL/drop" }
tokio = { version = "1", features = [ "rt" ] }

[dev-dependencies]
tokio = { version = "1", features = [ "macros", "rt-multi-thread" ] }